### PR TITLE
Updating versions of Cylon/Rolling Spider

### PR DESCRIPTION
**Pull request by alejandronanez**
Updating latest versions of Cylon and Rolling Spider packages.

### CODE REVIEW

**Comment by ChrisTheBaron** [comment]
Is this confirmed to fix issue #10? And can you change the dependencies to the following format? 

"cylon": "^1.2.0",
"rolling-spider": "^1.5.0"

Cheers, Chris

**Comment by alejandronanez** [comment]
Yeah, you can install the package once dependencies have been updated.
- [x] semver

**Comment by ChrisTheBaron** [comment]
Hey, 

Thanks for doing this. I will publish to npm tomorrow as version 1.2.0 

Cheers, Chris

**Comment by alejandronanez** [comment]
I really liked this project. My pleasure. ;)

**Comment by alejandronanez** [comment]
closes #10

**Pull request merged**
